### ISSUE TITLE
Suggestion: Intents should not be stateful objects.

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/API#12]
Currently intents are used as follows:

```
// how we locate the agent is platform specific - assuming it is a global in this example!
const agent = fdc3;

const context = {};
const intent = agent.intent("intent", context);

// at this point you can mutate the various properties
intent.target = "foo";

// when sending you can also change the context and target!
const result = await intent.send({foo: "bar"}, "MyApp")

// do something with the result
console.log(result);

// what state is the intent object in here? can I send again?
```

The above code snippet highlights quite a few ambiguities.

I'd propose a simpler API, that removes the `Intent` object altogether:

```
const agent = fdc3;

const context = {};
const intent = "DoSomething"
const result = await agent.sendIntent(intent, context);
console.log(result);
```

Much simpler!

**Comment by rikoe** [comment]
I couldn't agree more with this, and I am disappointed that this has not been discussed more.

I think for intents to be adopted successfully, the API needs to be really simple, and `const result = await agent.sendIntent("StartCall", context);` is simple and easy to understand without any ambiguities.

Stateful objects are unnecessary here, and makes for more complicated code to write.

**Comment by nkolba** [comment]
Completely agree with removing the Intent object and replacing with the _sendIntent_ method.  

Let's make the change.

**Comment by lauchlan** [comment]
Agree with Colin!

**Comment by rikoe** [comment]
@ColinEberhardt We can close this now after #26, I don't have the ability to.

**Comment by ColinEberhardt** [comment]
Great, thanks
