### ISSUE TITLE
Generated documentation in docs folder contain paths to contributors' forks

### ISSUE THREAD

**Issue by rikoe** [FDC3/API#16]
The README.md asks contributors to run `yarn run doc` after making changes, but this produces URI links ("Defined In") to their own forks.

This means that:
* These files change for every PR by a different contributor, polluting code diffs.
* These paths to forks get merged into the upstream repo still containing links to the fork, thereby making them incorrect.

These URI paths should either be relative, or always point to the upstream repo. If this is not possible, they should not be included at all, or generated documentation should not be checked in to the repo.

Example:
`*Defined in [interface.ts:41](https://github.com/ColinEberhardt/API/blob/eac0696/src/interface.ts#L41)*`

**Comment by rikoe** [comment]
@nkolba Changing the URLs themselves aren't good enough, you need to change the typedoc process, otherwise it is a problem for every PR. Please see my PR #32.

**Comment by nkolba** [comment]
Agreed, saw your PR after.  Let’s apply (though, the generated files are now in conflict- can you fix or remove them from the PR).
