### ISSUE TITLE
Should name in fdc3.open be an AppIdentifier?

### ISSUE THREAD

**Issue by rikoe** [FDC3/API#17]
The comment for `open(name: String, context: Context): Promise<void>` says _"Launches/links to an app by name"_.

Elsewhere (e.g. when sending an intent), `type AppIdentifier = String` is used. Is the "name" used in `open` the same as the app identifier used for intents? If it is the same, the same terminology should be used consistently.

If it is not the same, "name" needs to be explained in more detail to make the distinction clear. I would argue however that it should be the same app identifier used elsewhere if it is not, for the sake of API consistency.

In which case, it should probably be `open(name: AppIdentifier, context: Context)`

**Comment by nkolba** [comment]
For AppIdentifier and IntentName - let's change to String.

**Comment by rikoe** [comment]
Resolved by #26
