### ISSUE TITLE
Context in fdc3.resolve should be optional

### ISSUE THREAD

**Issue by rikoe** [FDC3/API#19]
It doesn't make sense for both the intent name and the context to be mandatory for a resolve operation.

In the [Hadouken implementation](https://github.com/HadoukenIO/fdc3-service/blob/86be5d5ce58c256fcf5d1a9eea164bbd2c80c0c3/src/client/index.ts#L46), it is defined as: 

`resolve(intent: IntentType, context?: Context): Promise<IApplication[]>`.

**Comment by nkolba** [comment]
@rikoe context optional w/PR#30

**Comment by rikoe** [comment]
Fixed with #30
