### ISSUE TITLE
Suggestion: Document the API via TypeScript

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/API#3]
Currently the API is documented in pseudo-code, which means some important detail is missing, e.g. `fdc3.open` returns a `Promise`, but it doesn't document what the promise resolves to?

I'd like to propose that the interface is documented as a TypeScript type definition. This should will give a more formal API specification that people can implement.

Note: this does not mean that implementations of the API must use TypeScript - it just provides a convenient format for specifying / documenting the interface

**Comment by nkolba** [comment]
Makes sense.
