### ISSUE TITLE
Resolve/findIntents: Falsy argument

### ISSUE THREAD

**Issue by rikoe** [FDC3/API#38]
The comments for `resolve`/`findIntents` states:

>  If intent argument is falsey, then all possible intents - and apps corresponding to the intents - are resolved for the provided context.

I would prefer if we are more explicit about the first argument than "falsy". It doesn't fit well into the TypeScript paradigm to accept multiple possible arguments with the same semantics.

I propose that we standardise on `null` and/or `undefined`. Thinking about it, `undefined` is probably better.

This would make the type definition:
`resolve(intent: String | undefined, context?: Context): Promise<Array<ActionMetadata>>;`
which is nice and explicit - either a string, or `undefined`.

**Comment by nkolba** [comment]
@rikoe can you make a PR for this?

**Comment by rikoe** [comment]
@nkolba I have a PR ready to go (see https://github.com/rikoe/API/pull/5), just need to get approval for it before I can submit.
