### ISSUE TITLE
Rename listener methods

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/API#39]
Currently we have the following:

```
intentListener(intent: String, handler: (context: Context) => void): Listener;
contextListener(handler: (context: Context) => void): Listener;
```

In keeping with web conventions (e.g. the DOM [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) method), and the standard approach of using 'verb phrases' for method names, I'd propose adding an `add` prefix to each:

```
addIntentListener(intent: String, handler: (context: Context) => void): Listener;
addContextListener(handler: (context: Context) => void): Listener;
```

**Comment by nkolba** [comment]
@ColinEberhardt can you make a PR for this?
