### ISSUE TITLE
Remove reliance on desktop agent being global

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/API#6]
Currently all of the API methods are defined as properties of a global `fdc3` object. This means that there can only ever be a single Desktop Agent within the current JS process. This might make sense now, but could be limiting in the future.

I'd suggest defining a non-global API, where methods are invoked on an Agent object. This object could be accessed via a global in the short-term, but would at least leave the door open for interacting with multiple agents.

For example this code:

```
fdc3.addIntentListener("ViewChart", console.log);
```

Would become:

```
const agent = fdc3.getAgent(); // obtain the current singleton
agent.addIntentListener("ViewChart", console.log);
```

This also makes it easier to mock / test the API.

**Comment by nkolba** [comment]
Good point Colin.  The global example was more just for the sake of example.  And in fact, as we start to prepare for an implementation on our side, we have moved away from global as well.  So, I will change to make explicit that it is not required to be a global - the namespacing of the API is up to the Desktop Agent implementation.

**Comment by ColinEberhardt** [comment]
> we have moved away from global as well

That's good news 👍 

> the namespacing of the API is up to the Desktop Agent implementation

That makes sense. To be precise, that means the API no longer needs a namespace - they are just a way of organising global objects, so would no longer be necessary. The API just describes the interface.

**Comment by nkolba** [comment]
added clarification about scopes.
